title: UH Classtellations
description: An Interactive Academic Visual Guide for UH Students
google_analytics:
show_downloads: false
theme: jekyll-theme-midnight
github:
  is_project_page: true
  repository_url: https://github.com/uh-classtellations/uh-classtellations
gems:
  - jekyll-mentions
